import streamlit as st
import random

# List of pickup lines
pickup_lines = [
    "Can I be your snowflake? I promise to never melt away from your heart",
    "Are you French? Because Eiffel for you",
    "Are you a Wi-Fi signal? Because I’m feeling a strong connection",
    "No pen, no paper...but, you still draw my attention",
    "Are you a heart? Because I'd never stop beating for you",
    "I believe in following my dreams, so you lead the way",
    "If being beautiful was a crime, you’d be on the most wanted list",
    "Kissing is a love language. Want to start a conversation with me?",
    "Are you iron? Because I don’t get enough of you",
    "Should we get coffee? Cause I like you a latte",
    "You should be Jasmine without the 'Jas'",
    "Are you a Disney ride? Because I'd wait forever for you",
    "Are you water? Because I'd die without you",
    "I see you like tequila. Does that mean you'll give me a shot?",
    "Hey, I’m sorry to bother you, but my phone must be broken because it doesn’t seem to have your number in it",
    "Are you a boxer? Because you're a total knockout",
    "Are you public speaking? Because you make me really nervous",
    "Are you good at math? Me neither, the only number I care about is yours",
    "I'm not a photographer, but I can picture us together",
    "Are you an exam? Because my mom told me not to cheat on important things",
    "Hi. I’m Mrs./Mr. Right. Someone said you were looking for me",
    "Einstein said that nothing is faster than the speed of light. But he never saw how fast I would fall for you",
    "When we met, it was like listening to a song for the first time that I knew would eventually become my favorite",
    "I see you’re a fan of vodka. Does that mean you’ll give me a shot?",
    "All the pickup lines are taken, but are you?",
    "I'm not a physicist, but I feel a strong magnetic attraction here. Is it just me?",
    "I'm no geologist, but I feel a seismic shift in my world whenever you’re near",
    "Is your name Google? Because you’ve got everything I’ve been searching for",
    "You must be a high test score because I want to take you home and show you to my mother",
    "Hey. I’m the one you’ve been looking for. You can delete this app now",
    "Numbers start with 1 2 3. The alphabet starts with A B C. But the universe starts with U N I",
    "You owe me a drink because I dropped mine when I saw you",
    "You must be an important line in a book because seeing you is a highlight",
    "Are you Nemo? Because I've been trying to find you",
    "Are you a bank loan? Because you have my interest",
    "I hope you know CPR, because you just took my breath away",
    "Are you the sun? Because I could stare at you all day, and it’d be worth the risk",
    "Are you a beaver? Because DAM!",
    "Are you a keyboard? Because you're just my type",
    "My mom said sharing is caring but, no...you're all mine!",
    "Are you John Cena? Because I've never Cena girl like you before",
    "It's time to pay up. It's the first of the month, and you've been living in my mind rent-free",
    "Are you a light? Because you always make me feel bright",
    "Just so you know, I'm a felon...because I felon love with you",
    "Do you like Star Wars? Cause Yoda only one for me",
    "Are you chicken fingers and fries? Because I don't care how many options I have, I will always choose you",
    "It's a good thing I have a library card because I've been checking you out",
    "Do you have a bandaid? My knees hurt from falling for you",
    "We may not be pants, but we'd make a great pair",
    "You know what's beautiful? Repeat the first word",
    "Your eyes remind me of Ikea: easy to get lost in",
    "Can I borrow a kiss? I promise to give one back",
    "If you were a Transformer, you'd be Optimus Fine",
    "Are you the sun? Because you're hot",
    "Are you a vape? Because I'd never use you",
    "Can I get your jersey? Because I want your name and number",
    "I must be a time traveler, because I can't imagine my future without you",
    "Do you believe in love at first sight, or should I walk by again?",
    "Are you a light switch? Because you turn me on",
    "Are you a doctor? Because you instantly make me feel better",
    "You must be a masterpiece, because I can't take my eyes off of you",
    "Are you made of cheese? Because you're looking Gouda!",
    "Are you my favorite song? Because I can't get you out of my head",
    "I'm no photographer, but I can picture us together",
    "Are you a diamond? Because you shine so bright!",
    "Do you like fishing? Because you have me hooked",
    "Are you a dream? Because I don't want to wake up",
    "If you were a fruit, you'd be a fine-apple",
    "If I could rearrange the alphabet, I'd put U and I together",
    "Kiss me if I'm wrong, but the Earth is definitely flat",
    "Are you a phone charger? Because I'm dying without you",
    "What's your name again? Can I call you mine?",
    "Are you a parking ticket? Because you've got fine written all over you",
    "Are you a triangle? Because you're acute one",
    "I'm Microsoft. Can I crash your place tonight?",
    "Have you ever been to jail? Because it should be illegal to be that good-looking",
    "Did we go to school together? I could have sworn we had chemistry",
    "Can I buy you a drink? I’d like to see how good you are at swallowing",
    "Kiss me if I’m wrong but, the earth is for sure flat",
    "You must be my lucky charm, because you’re magically delicious!",
    "This date has been a big bowl of ‘frosted flakes’! It’s GRRRRRREAT!",
    "Where in Asia are you from? I can totally see myself in Ja-Panties!",
    "Flip this coin! Mama’s got a 50/50 chance at getting some tail tonight",
    "Are you a toaster? Because I am looking for something to take a bath with tonight",
    "You want to know my favorite tea? I’m looking at her, shawTea!",
    "It doesn’t matter to me what you’ve got in your pants. Just as long as you can take what’s in mine!",
    "Ow! I just bit my lip. Can you kiss it and make it better?",
    "I can’t taste my cherry lip gloss! Can you give it a try?",
    "Hey boy, want to play shark attack? You eat! I-scream!",
    "I’m so jealous of your heart right now, because it’s pounding inside of you and I’m not",
    "(follows behind a love interest for a while) Don’t mind me! I’m just following my dreams",
    "(approaching a hostess stand) I’d like to make reservations for two. “What time?” Whenever you’re free",
    "Is that a beaver I see, because GOD DAM!",
    "I’m not quite Jesus, I’m more of an apostle. I could never turn water into wine. But I bet I can turn you into mine",
    "I don’t care if you’re vegan. I got the only meat you’ll ever need",
    "Are you a construction worker? Because I see a dump truck back there! Cla-Clow!",
    "If you were a room in my house I’d make you the basement. So I could put kids inside you",
    "Are you from France? Cause MaDAMN you fine!",
    "I’m no cashier but you got a couple things on you I’d like to check out!",
    "When I was a kid I used to have to chase butterflies. Now you’re over here bringing them right to me",
    "If you’re a fruit, you’d be a FINEapple. If you were a vegetable, I’d be your life support",
    "You want to know why I’m always thinking about you? Because my mom told me to think about my future",
    "I always thought happiness started with the letter H. But my happiness starts with U",
    "Are you part phone charger? Cause, I’m dying without you!",
    "Are you good at algebra? Because you could replace my ex without asking Y!",
    "Do you like soccer? My favorite player is Ronaldo, but we can get MESSI!",
    "I’d like to take you to the movies, but they don’t allow outside SNACKS",
    "I’m no waitress, but boy I’ll take your tip",
    "Can I take your picture? I need it to show Santa what I want for Christmas",
    "Your body is 60% water, and I’m thirsty as FUCK",
    "Stop right there or I’m calling the cops! Because you stole my heart",
    "ethplkkrf#4752! (What’s that?) The WiFi password for when you come over later",
    "You’re so hot I just forgot my pickup line",
    "I don’t subscribe to Netflix but I think we should make our own movie",
    "Of all four seasons you’re definitely winter, because soon you’ll be coming",
    "Relationships should be 50/50. You give me your last name and I’ll scream out your first",
    "Hey boy, I just got some Boba Tea, but I bet it won’t be the last time I get balls in my mouth today",
    "I got us sushi for dinner, but that won’t be the only thing we do raw tonight",
    "I had sushi for lunch, it won’t be the last time I go down on something fishy today",
    "You got no paper and no pencil but still you’re drawing my attention",
    "That must be why the sky is so gray, all the color is in your eyes",
    "Are you hiring? Because you look like you have a couple openings that need filling",
    "Are you a subway sandwich artist? I’m hoping you can hook me up with a footlong!",
    "Right now you’re looking like my keyboard, because you’re just my type",
    "Kissing is a love language. Want to start a conversation with me?",
    "Close your eyes and what do you see? (Nothing, Darkness, Black, etc.) That’s my life without you",
    "My crush is ugly…without the GLY",
    "You’re magnetic! My zipper is falling for you",
    "My therapist tells me I’m Type-A, because I’m always on top of things. How’d you like to be one of them?",
    "You look like the scariest haunted house because I’m going to scream so loud when I’m inside you"
]

# Function to generate a random pickup line
def generate_rizz():
    return random.choice(pickup_lines)

# Streamlit app
st.title("Rizz Line Generator")

if st.button("Generate Rizz"):
    line = generate_rizz()
    st.write(line)
    st.write("Click the button below to copy the line to clipboard.")
    st.button("Copy", on_click=st.write("Line copied to clipboard!"))
